set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'

#set -g @plugin 'catppuccin/tmux#v2.1.2'
# set -g @catppuccin_flavor 'mocha' 
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_show_battery_widget 1

run '~/.tmux/plugins/tpm/tpm'
